remote_theme: pages-themes/cayman@v0.2.0
title: "Stories from an Azure Developer"
twitter_username: rich_ross
github_username: richross
description: "Stories from an Azure Developer"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://richross.github.io" # the base hostname & protocol for your site, e.g. http://example.com

plugins:
  - jekyll-feed
  - jekyll-remote-theme